backend:
  name: github
  repo: fandcomp/caaip-website
  branch: main
  base_url: https://caaip-website.vercel.app
  auth_endpoint: /api/auth

media_folder: "public/images"
public_folder: "/images"

site_url: "https://caaip-website.vercel.app"
display_url: "https://caaip-website.vercel.app"
logo_url: "/images/logo-itb.png"

publish_mode: editorial_workflow

# Media Library Configuration
media_library:
  name: cloudinary
  config:
    cloud_name: YOUR_CLOUD_NAME
    api_key: YOUR_API_KEY

collections:
  # === PENGATURAN WEBSITE ===
  - name: settings
    label: "Pengaturan Website"
    files:
      - name: general
        label: "Pengaturan Umum"
        file: "content/settings/general.yml"
        fields:
          - {label: "Nama Institusi", name: "site_name", widget: "string", default: "CAAIP"}
          - {label: "Tagline", name: "tagline", widget: "string", default: "Pusat Pendidikan dan Pelatihan Transportasi Udara"}
          - {label: "Deskripsi Website", name: "description", widget: "text"}
          - {label: "Logo Utama", name: "logo", widget: "image", choose_url: false}
          - {label: "Logo Kemenhub", name: "logo_kemenhub", widget: "image", choose_url: false}
          - {label: "Email Kontak", name: "contact_email", widget: "string", default: "info@caaip.ac.id"}
          - {label: "Alamat", name: "address", widget: "text"}
          - {label: "Telepon", name: "phone", widget: "string"}
          - {label: "WhatsApp", name: "whatsapp", widget: "string"}
          - {label: "Bahasa Default", name: "default_locale", widget: "select", options: ["id","en"], default: "id"}

      - name: social_media
        label: "Media Sosial"
        file: "content/settings/social.yml"
        fields:
          - {label: "Facebook", name: "facebook", widget: "string", required: false}
          - {label: "Instagram", name: "instagram", widget: "string", required: false}
          - {label: "Twitter/X", name: "twitter", widget: "string", required: false}
          - {label: "YouTube", name: "youtube", widget: "string", required: false}
          - {label: "LinkedIn", name: "linkedin", widget: "string", required: false}
          - {label: "TikTok", name: "tiktok", widget: "string", required: false}

  # === HALAMAN STATIS ===
  - name: pages
    label: "Halaman Statis"
    folder: "content/pages"
    create: true
    slug: "{{slug}}"
    preview_path: "{{locale}}/{{slug}}"
    fields:
      - {label: "Status", name: "status", widget: "select", options: ["draft","published"], default: "draft"}
      - {label: "Judul Halaman", name: "title", widget: "string"}
      - {label: "Slug URL", name: "slug", widget: "string", hint: "URL halaman (contoh: tentang-caaip)"}
      - {label: "Bahasa", name: "locale", widget: "select", options: ["id","en"], default: "id"}
      - {label: "Tampil di Menu", name: "show_in_menu", widget: "boolean", default: true}
      - {label: "Urutan Menu", name: "menu_order", widget: "number", value_type: "int", default: 0}
      - {label: "Gambar Header", name: "hero_image", widget: "image", required: false, choose_url: false}
      - {label: "Ringkasan", name: "summary", widget: "text", required: false}
      - {label: "Konten", name: "body", widget: "markdown"}

  # === AGENDA & EVENT ===
  - name: agenda
    label: "Agenda & Event"
    folder: "content/agenda"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    preview_path: "{{locale}}/agenda/{{slug}}"
    fields:
      - {label: "Status", name: "status", widget: "select", options: ["draft","published"], default: "draft"}
      - {label: "Judul Event", name: "title", widget: "string"}
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Tanggal Mulai", name: "start_date", widget: "datetime", format: "YYYY-MM-DD", time_format: "HH:mm"}
      - {label: "Tanggal Selesai", name: "end_date", widget: "datetime", format: "YYYY-MM-DD", time_format: "HH:mm", required: false}
      - {label: "Lokasi", name: "location", widget: "string"}
      - {label: "Jenis Event", name: "event_type", widget: "select", options: ["Seminar","Workshop","Pelatihan","Konferensi","Lainnya"], default: "Lainnya"}
      - {label: "Poster/Gambar", name: "poster", widget: "image", required: false, choose_url: false}
      - {label: "Pembicara", name: "speakers", widget: "list", field: {label: "Nama Pembicara", name: "name", widget: "string"}, required: false}
      - {label: "Kapasitas Peserta", name: "capacity", widget: "number", value_type: "int", required: false}
      - {label: "Pendaftaran Dibuka", name: "registration_open", widget: "boolean", default: false}
      - {label: "Link Pendaftaran", name: "registration_link", widget: "string", required: false}
      - {label: "Ringkasan", name: "summary", widget: "text"}
      - {label: "Bahasa", name: "locale", widget: "select", options: ["id","en"], default: "id"}
      - {label: "Detail Lengkap", name: "body", widget: "markdown"}

  - name: berita
    label: "Berita"
    folder: "content/berita"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    preview_path: "{{locale}}/berita/{{slug}}"
    fields:
      - {label: "Status", name: "status", widget: "select", options: ["draft","published"], default: "draft"}
      - {label: "Judul", name: "title", widget: "string"}
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Tanggal", name: "date", widget: "datetime", format: "YYYY-MM-DD", time_format: false}
      - {label: "Penulis", name: "author", widget: "string", default: "Redaksi"}
      - {label: "Kategori", name: "category", widget: "select", options: ["Berita Internal","Berita Eksternal","Pengumuman","Lainnya"], default: "Berita Internal"}
      - {label: "Tag", name: "tags", widget: "list", default: []}
      - {label: "Cover", name: "cover", widget: "image", choose_url: false}
      - {label: "Ringkasan", name: "summary", widget: "text"}
      - {label: "Bahasa", name: "locale", widget: "select", options: ["id","en"], default: "id"}
      - {label: "Isi", name: "body", widget: "markdown"}

  - name: kabar_duka
    label: "Kabar Duka"
    folder: "content/kabar-duka"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    preview_path: "{{locale}}/kabar-duka/{{slug}}"
    fields:
      - {label: "Status", name: "status", widget: "select", options: ["draft","published"], default: "draft"}
      - {label: "Judul Obituari", name: "obituaryTitle", widget: "string"}
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Nama", name: "name", widget: "string"}
      - {label: "Foto", name: "photo", widget: "image", required: false, choose_url: false}
      - {label: "Afiliasi", name: "affiliation", widget: "string", required: false}
      - {label: "Peran", name: "role", widget: "select", options: ["Dosen","Staf","Alumni","Lainnya"], required: false}
      - {label: "Tanggal Wafat", name: "dateOfDeath", widget: "datetime", format: "YYYY-MM-DD", time_format: false}
      - {label: "Info Prosesi", name: "funeralInfo", widget: "text", required: false}
      - {label: "Lokasi", name: "location", widget: "string", required: false}
      - {label: "Kontak Keluarga", name: "contactFamily", widget: "string", required: false}
      - {label: "Galeri", name: "gallery", widget: "list", field: {label: "Gambar", name: "image", widget: "image"}, required: false}
      - {label: "Ringkasan", name: "summary", widget: "text"}
      - {label: "Bahasa", name: "locale", widget: "select", options: ["id","en"], default: "id"}
      - {label: "Isi", name: "body", widget: "markdown"}

  - name: profil
    label: "Profil"
    folder: "content/profil"
    create: false
    fields:
      - {label: "Judul", name: "title", widget: "string"}
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Ringkasan", name: "summary", widget: "text", required: false}
      - {label: "Bahasa", name: "locale", widget: "select", options: ["id","en"], default: "id"}
      - {label: "Isi", name: "body", widget: "markdown"}

  - name: alumni_orang
    label: "Alumni - Orang"
    folder: "content/alumni/orang"
    create: true
    slug: "{{cohort}}-{{slug}}"
    preview_path: "{{locale}}/alumni/{{cohort}}"
    fields:
      - {label: "Status", name: "status", widget: "select", options: ["draft","published"], default: "published"}
      - {label: "Nama", name: "name", widget: "string"}
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Angkatan", name: "cohort", widget: "number", value_type: "int", min: 1900, max: 2100}
      - {label: "Program", name: "program", widget: "string", required: false}
      - {label: "Unit", name: "unit", widget: "string", required: false}
      - {label: "Jabatan", name: "jobTitle", widget: "string", required: false}
      - {label: "Organisasi", name: "organization", widget: "string", required: false}
      - {label: "Email (opsional)", name: "email", widget: "string", required: false}
      - {label: "Telepon (opsional)", name: "phone", widget: "string", required: false}
      - {label: "Foto", name: "avatar", widget: "image", required: false, choose_url: false}
      - {label: "Bahasa", name: "locale", widget: "select", options: ["id","en"], default: "id"}
      - {label: "Bio Singkat", name: "body", widget: "markdown", required: false}